### ISSUE TITLE
Twitter APIの使い方を調べる

### ISSUE THREAD

**Issue by t-morisawa** [t-morisawa/rekognition#18]
やりたいこと：特定のユーザのメディア（画像）を取得する

APIリファレンス
https://developer.twitter.com/en/docs/twitter-api

**Comment by hikarukoizumi** [comment]
https://tma15.github.io/blog/2020/08/02/pythontwitter-apiを利用してツイートを検索画像いいねリツイートの取得も/

http://pppurple.hatenablog.com/entry/2016/04/02/204119

・Python twitterライブラリ
https://qiita.com/kitarikes/items/543ab75a379f0bf903cc
