### ISSUE TITLE
[Twitter]時系列順に並ぶようにする

### ISSUE THREAD

**Issue by t-morisawa** [t-morisawa/rekognition#32]
https://blog.amedama.jp/entry/2015/12/14/013805

tweetsオブジェクトをtweets.timestampでソートする例

```
sorted(tweets, key=tweets.timestamp)
sorted(tweets, key=tweets.timestamp, reverse=True)
```

**Comment by hikarukoizumi** [comment]
・search_results.created_at
　フォーマット：2016-08-02 10:00:00

・文字列変換して並び替える
https://kazusa-pg.com/python-strftime-strptime/#toc2

**Comment by t-morisawa** [comment]
https://github.com/t-morisawa/rekognition/pull/47
